spring:
  application:
    name: conf-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moahmmedfah2002/server-conf-pfs.git
          default-label: main
server:
  port: 9000
